version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: lkz-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    ports:
     - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  .postgres-data:
